
import '../App.css'
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import * as React from 'react';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Link } from 'react-router-dom';
import Header from "../Home/Header";

function CaseHistoricOverviewIrish({ changeIrish, setChangeIrish }) {

    return (
        <>

            <h3 style={{ textAlign: "center", padding: "10px", color: 'maroon' }}>Léargas Ginearálta Staire</h3>

            <p className='para-style'>
                Bhí cúrsaí liteartha beo bríomhar in Éirinn sa Nua-Aois Luath. Taobh thiar den saibhreas cultúrtha seo bhí an tír lán d'achrann polaitiúil, coinbhleacht, agus foréigean an choilíneachais. Tosaíonn MACMORRIS leis an bhliain 1541, nuair a chuaigh Act of Kingly Title tríd an pharlaimint in Éirinn, a thug teideal Rí na hÉireann d'Éinrí VIII  agus dá oidhrí, agus bunaíodh Ríocht na hÉireann. Ina dhiaidh sin, tháinig Concas na dTúdarach agus borradh faoi thionchar agus smacht na Sasanach ar Éirinn. Bhí an concas faoi cheannasaíocht Fir Ionaid an Rí, leithéidí Anthony St Leger,  Thomas Radclyffe,  William Fitzwilliam  agus Henry Sidney,  a raibh sé i gceist acu talamh a bhaint ó na dúchasaigh trí pholasaithe ar nós géilleadh agus athbhronnadh – cuireadh brú ar thiarnaí Gaelacha a gcuid talún a ghéilleadh don choróin, ach go dtabharfaí ar ais dóibh í, chomh maith le teideal Sasanach, dá mbeidís dílis don rí agus dá gcuirfidís nósanna agus cleachtas na Sasanach chun tosaigh (féach Conn Bacach Ó Néill,  Iarla Thír Eóghain, Muircheartach Ó Briain , Iarla Thuamhain, agus Domhnall Mac Carthaigh Mór,  Iarla Chlann Charthaigh).

                Mar chuid den choncas, bhunaigh Henry Sidney  uachtaránacht Chúige Mumhan, duine a bheadh freagrach don Fhear Ionaid, ach go mbeadh údarás iomlán ag an duine sin ar Chúige Mumhan. Ní ról é a bhí gan deacrachtaí agus fadhbanna, áfach.

            </p>
            <h5>
                An tÉirí Amach i nDeasumhain</h5>
            <p className='para-style'>
                Bhraith na Gearaltaigh i nDeasumhain go raibh an t-athrú seo ag cur isteach ar an tionchar a bhí acu féin, agus chuir siad in éadan na huachtaránachta nua. Mar gheall air sin, agus mar gheall ar an choimhlint idir Mac Gearailt agus de Buitléar in Urumhain, gabhadh Iarla Dheasumhan Gearóid (mac Séamais) Mac Gearailt  agus cuireadh i dTúr Londan é sa bhliain 1568.  Bliain ina dhiaidh sin, d'éirigh na Gearaltaigh amach faoi cheannasaíocht Shéamais (mac Muiris) Mhic Gearailt,  agus rinne siad ionsaithe ar na Sasanaigh agus ar a lucht tacaíochta thar tréimhse 4 bliana. Rinne siad creachadh ar Chill Mocheallóg  sa bhliain 1571, ach faoin bhliain 1573 tháinig deireadh leis an éirí amach gan tairbhe agus theith Mac Gearailt  go dtí an Spáinn.

                Ina dhiaidh sin, ligeadh saor Iarla Dheasumhan agus chaith sé 5 bliana ag déanamh iarrachta cothromaíocht a aimsiú idir ceannaireacht a theaghlaigh a chinntiú dó féin agus na Sasanaigh a shásamh. Faoin bhliain 1579, áfach, d'fhill Séamas (mac Muiris) Mac Gearailt  ón Spáinn – leagáid an Phápa Nicholas Sanders  agus arma in éineacht leis – ag cur túis leis
                an Dara hÉirí Amach i nDeasumhain, agus tugadh fealltóir ar Iarla Dheasumhan.  Chuir na Sasanaigh feachtas fuilteach foréigneach ar bun in éadan na nGearaltach agus idir an dhá dream scriosadh Cúige Mumhan.  Ar na heachtraí a bhfuil cuntas againn orthu, tá an sléacht gar do Choill Mhór , coinbhleacht ar Ghort na Tiobrad,  agus cathanna ag Carraig an Phoill.   An sléacht is mó a sheasann amach, áfach, ná an méid a tharla ag Dún an Óir  sa bhliain 1580. Tharla sé idir mí Mhéan Fómhair agus mí Dheireadh Fómhair i ndún ar an taobh thiar de Chuan Ard na Caithne. Meastar gur tháinig suas le 800 Iodálach agus Spáinneach d'fhórsaí an Phápa i dtír sa chuan le cuidiú a thabhairt do na Gearaltaigh. Cuireadh na fórsaí seo faoi imshuí sa dún, áfach, agus i mí Dheireadh Fómhair chuir fórsaí an Tiarna Grey  an dún faoi léigear. Faoi cheann trí lá, ghéill fórsaí an Phápa agus cuireadh chun báis iad ar an láthair. Mar gheall ar pholasaí rualoiscthe Grey  agus an Iarla Urumhan,  bhí an bua faighte acu ar fhórsaí na nGearaltach faoin bhliain 1581. Cuireadh an tóir ar Iarla Dheasumhan , agus maraíodh Seaán (mac Séamais) Mac Gearailt  sa bhliain 1582 – cumadh an marbhna “Truagh sin, a chinn mo chroidhe”  don Seaán seo. Idir 1581 agus 1583, níor gabhadh an tIarla, agus cúpla uair is beag nár gabhadh, mar a tharla ar Shliabh Luachra.  Faoi dheireadh, i mí na Samhna 1583, gabhadh é gar do Thrá Lí agus baineadh an ceann de go gairid ina dhiaidh sin gar do Ghleann na Ginte.  Tugadh a cheann d'Iarla Urumhan i gcathair Chorcaí agus taispeánadh é ina dhiaidh sin ar Dhroichead Londan.

            </p>
            <h5> Plandáil na Mumhan</h5>

            <p className='para-style'>
                Nuair a theip ar an éirí amach, ghabh an choróin seilbh ar thalamh Iarla Dheasumhan.   Bronnadh an talamh seo, chomh maith le talamh lucht tacaíochta an Iarla, ar na Nua-Ghaill (.i. coilínigh nua a tugadh isteach sa tír as an Bhreatain) a raibh sé de dhualgas orthu an tír a athdhaonrú, a atheagrú, agus a chur chun tairbhe dóibh féin agus don choróin. Cuid lárnach den phróiseas seo ná suirbhéireacht a dhéanamh ar an talamh a gabhadh, ar an luach a bhaint léi, agus cuntas a choinneáil ar an sealbhóir reatha. I measc na suirbhéanna is luachmhaire atá againn tá The Desmond Survey agus The Peyton Survey, a rinne coimisinéirí a ceapadh sa bhliain 1584. Léirigh an tsuirbhéireacht an méid talún a bhí faoi smacht ag an rialtas, agus chuidigh sé leis an phróiseas plean a dhréachtú do phlandáil na Mumhan. Tríd an tsuirbhéireacht seo, léiríodh gnéithe d'ailtireacht an réigiúin, cosúil leis an chur síos ar Chaisleán Bouchier  agus ar Chaisleán Eas Géitine,  agus tugadh aird ar acmhainní nádúrtha ar nós iascaireacht bhradán agus eascann sa Daoil.

                Cé go raibh bhí sé beartaithe ar dtús talamh a bhronnadh ar 85 duine sa chéad chuid den phlandáil, sa bhliain 1588 bronnadh tiarnais ar 35 duine, an chuid is mó díobh sin ceannasaithe airm nó fir riaracháin ag obair in Éirinn a bhí iontu. An fear is mó a bhfuil cáil air astu sin ná Sir Walter Raleigh,  ar bronnadh 40,000 acra air in oirthear Chorcaí agus iarthar Phort Láirge lena n-áiríodh Eochall  agus Lios Mór.   Fear eile a raibh baint aige le heastát Raleigh ná an taiscéalaí Thomas Hariot  a chaith tamall i Mainistir Mhaolanfaidh . Fear eile a fuair talamh ná William Herbert , a chum an tráchtas Laidine Croftus, sive de Hibernia liber  – bronnadh Oileán Chiarraí   air chomh maith leis an talamh timpeall air, 13276 acra san iomlán. Bronnadh 6000 acra, lena n-áiríodh Mala,  ar Thomas Norris,  a ndearnadh Uachtarán na Mumhan de ina dhiaidh sin. Bronnadh 10910 acra i gCo. Phort Láirge ar Thiarna-Seansailéir Sasana, Christopher Hatton  (ar chum Barnaby Rich  agus Thomas Churchyard  saothair dó). Bronnadh 3028 acra timpeall Chill Cholmáin  ar Edmund Spenser,  údar Faerie Queene.  Bhí roinnt deacrachtaí ag na fir seo ón tús. Ní raibh siad riamh ábalta na cuótaí d'oibrithe as Sasana a chomhlíonadh, agus mar sin bhí siad ag brath ar oibrithe áitiúla. Chuir cásanna dlí ó na dúchasaigh moill ar an dul chun cinn, mar a léiríonn an cás dlí idir Muiris de Róisde  agus Spenser i dtaca le Cill Cholmáin.   Faoin bhliain 1598, mhill fórsaí Aodha Mhéig Uidhir  an phlandáil le linn Chogadh na Naoi mBliana, agus leagadh Cill Cholmáin  chun talaimh. Theith Spenser go Londain agus fuair sé bás go gairid ina dhiaidh sin (féach Edmund Spenser i gCúige Mumhan).

            </p>
            <h5>  Cath Chionn tSáile (1601)</h5>
            <p className='para-style'>
                Bhí milleadh Phlandáil na Mumhan i measc buanna eile a bhí ag Aodh O'Neill  agus a chomhghuaillithe sna blianta cogaíochta 1593–1600. Bhí an cailleadh ba mhó acu, áfach, i gCath Chionn tSáile  in 1601, cath a chuir cor i gcinniúint an chogaidh.   Bhí tacaíocht ábharach ag teacht isteach ón Spáinn chuig Ó Néill ar feadh blianta, agus i bhfómhar na bliana 1601 cuireadh c.4500 Spáinneach chuig Cúige Mumhan. Ach mar gheall ar stoirm, bhí ar an chuid is mó de na loing sin casadh ar ais agus níor tháinig ach 1700 saighdeoir i dtír i gCionn tSáile , iad faoi cheannasaíocht Don Juan del Águila.  D'éirigh leo an baile a ghabháil gan mórán deacrachta i mí Mheán Fómhair 1601. Thug Mountjoy  freagra gasta air seo agus d'ordaigh sé go ndéanfadh a arm léigear ar an bhaile. Tháinig Ó Néill  agus Ó Domhnaill  aduaidh le tacaíocht a thabhairt do na Spáinnigh, ag cur coisc ar línte soláthair na Sasanach ar an bhealach. Tháinig trúpaí breise ón Spáinn i dtír ag Gleann Bearcháin  faoi mhí na Nollag, agus chuir siadsan agus del Águila  plean le chéile: bhrúfadh arm Uí Néill i dtreo línte na Sasanach ionas gur féidir leo an léigear a bhriseadh agus go mbeadh na Spáinnigh in ann Cionn tSáile a fhágáil agus teacht le chéile leis na fórsaí Éireannacha. Cuireadh i bhfeidhm an plean seo ar 24ú Nollaig agus theip air go tubaisteach. Cuireadh an ruaig ar na hÉireannaigh agus ar na Spáinnigh, ghéill Don Juan del Águila  agus theith Ó Néill ar ais ó thuaidh. Mar gur eachtra chomh suntasach é seo i gCogadh na Naoi mBliana, tá go leor peirspictíochtaí éagsúla air. Is féidir amharc ar Chionn tSáile   ar léarscáil MACMORRIS agus dearcadh na Sasanach a fháil ó chuntas Mounjoy , dearcadh na nGael a fháil ó chuntas na nAnnála leis na Ceithre Máistrí, chomh maith dearcadh na Spáinneach a fháil trína gcuntais féin (faoin bhaile ar ar thug siad Quinzal). I ndiaidh an chatha, ghéill na Spáinnigh na daingin i nDún Baoi , Dún na Séad  agus Gleann Bearcháin.  Brúdh siar go leor de na tiarnaí Gaelacha go dtí gur theith timpeall nócha acu go dtí an Spáinn sa bhliain 1607, eachtra ar a dtugtar Teitheadh na nIarlaí.

                Chuir sé seo tús le tréimhse eile lán le hathruithe agus teannas creidimh; baineann an tréimhse seo le Plandáil Uladh, coilínigh Phrotastúnacha ag teacht isteach as Albain agus Sasana, agus gearáin ó shealbhóirí Caitliceacha talún i dtaca le pleananna Cúige Chonnacht a phlandáil agus leis an dóigh ar caitheadh leosan i bparlaimintí na hÉireann sna 1620–1630daí.
            </p>
            <h5> Freagraí Liteartha</h5>
            <p className='para-style'>
                Le linn na tréimhse seo a bhí lán le coinbhleacht agus anord polaitíochta, bhí go leor daoine ag scríobh agus ag tabhairt tuairimí faoin mhéid a bhí ag titim amach thart orthu. Bhí na scoileanna filíochta Gaeilge faoi bhláth, ag cur oiliúna ar na filidh (filí gairmiúla) a raibh an tábhacht agus stádas sóisialta ar leith a bhí acu in uasalaicme na nGael anois á chailliúint acu (féach Cad atá i gceist le Filíocht na Sgol?  agus Úsáid foinsí Gaeilge ). Bhí gnéithe den Fhrith-Reifirméisean ag teacht chun tosaigh i scoláireacht na nua-Laidine, ní hamháin i saothar diagachta ar nós Historiae Catholicae Iberniae compendium  le Pilib Ó Súilleabháin Béirre , ach i saothar tuata chomh maith cosúil le Ormonius  le Diarmaid Ó Meadhra.  Ag an am céanna, bhí beocht ar leith i measc na Nua-Ghall chomh maith, léirithe ag leithéid Richard Stanihurst  ina shaothar Holinshed’s Chronicles , lena n-áirítear a mholadh ar Domhnall Dubh Ó Cathail  as Achadh Deo  agus a aistriúchán turgnamhach ar Virgil his Aeneid. B'fhéidir go bhfuil cuma thraidisiúnta go leor ar bhailiúchán soinéad Richard Nugent, Cynthia,  a foilsíodh sa bhliain 1602, ach tá gnéithe de líonra Nugent,  go háirithe gníomhaíocht chultúrtha a theaghlaigh, a léiríonn ilghnéitheacht teanga thart air: chum a athair, William Nugent,  arbh fhile soinéad é, filíocht Ghaeilge ar ábhar na deoraíochta i ndeibhibhe, meadaracht san fhilíocht Chlasaiceach: Diombáidh triall ó thulchaibh Fáil  agus Fada i n-éagmais inse Fáil .  Chum Christopher Nugent,  uncail Richard, Barún Dealbhna, treoirleabhar Gaeilge  (frásaí taobh le taobh i nGaeilge, Béarla agus Laidin) le Banríon Eilís I  a spreagadh chun an Ghaeilge a fhoghlaim ('to understande the language of your people theare'). Bhí filí oidhreachtúla faoi phátrúnacht na Núinseannach, muintir Chobhthaigh, cosúil le Muircheartach Ó Cobhthaigh  a chum Do-ní clú áit oighreachda  agus Geall re hiarlachd ainm barúin  do William Nugent agus Christopher Nugent faoi seach. Tá na fir seo mar chuid de liosta leathan d'údair is de shaothar atá anois mar chuid de bhunachar sonraí MACMORRIS, agus cé nach bhfuil sé go hiomlán cuimsitheach, is é an bunachar sonraí is mó agus is cuimsithí a bhaineann le bunfhoinsí eolais ar Éirinn sa tréimhse seo. Is féidir saothair sa bhunachar seo a chuardach , nó más fearr leat breathnú trí na saothair sin ar bhealach físiúil, is féidir leas a bhaint as na líonraí saothar  le nascanna a fheiceáil idir téacsanna agus daoine, áit a dtarraingíonn muid le chéile údair, filí, clódóirí, foilsitheoirí, agus pátrúin a bhaineann le gach téacs.

                Faoi na 1570daí, bhí an ilghnéitheacht chultúrtha le feiceáil cheana féin sa tír a raibh Sean-Ghaill agus Gaeil ag meascadh, agus d'éirigh sí níos casta arís le teacht saighdeoirí, riarthóirí agus coilínigh na Nua-Ghall – gníomhairí i gConcas na dTúdarach a raibh ceangal acu leis an Éirí Amach i nDeasumhain, le Plandáil na Mumhan, agus le Cath Chionn tSáile. Ar na gnéithe is spéisiúla faoin choncas tá an méid scríbhneoirí a bhí ann go luath. Ina measc sin tá na fir a luadh thuas – Thomas Churchyard,  Thomas Hariot,  William Herbert,  Sir Walter Raleigh,  Barnaby Rich,  agus Edmund Spenser.  Taobh leosan tá John Harrington,   aistritheoir Orlando Furioso , agus údar roinnt leabhar burdún   a dhéanann cur síos (i measc rudaí eile) ar Dhún Canann  agus ar Mhuiris éigin ag damhsa in Áth Dara.  Ansin tá Lodowick Bryskett , a mholann Spenser in A discourse of ciuill life;  agus Fynes Moryson,  a dhéanann plé ar Phápairí Sotalacha i gCathair Chorcaí  ina leabhar taistil.

                Tugann MACMORRIS an deis dúinn machnamh a dhéanamh ar an dóigh a dtuigeann muid an stair ón litríocht, agus ar na peirspictíochtaí éagsúla atá ar fáil againn ar na heachtraí tábhachtacha staire seo. Trí na líonraí , is féidir a fheiceáil cé na daoine a raibh aithne acu ar a chéile, agus cé na nascanna a bhí acu le heachtraí agus daoine sa saol polaitiúil; is féidir an Léarscáil Dhomhain  a úsáid le breathnú trí na téacsanna agus na húdair bunaithe ar na háiteanna a bhfuil baint acu leo. Níl sé i gceist againn freagraí a chur ar fáil, ach taiscéalaíocht a spreagadh, agus aird a tharraingt ar gach sórt léargais atá ar fáil againn ar an tréimhse fhíorspéisiúil seo.
            </p>
        </>



    );
}

export default CaseHistoricOverviewIrish;
